name: TestRunner
run-name: 测试
on:
  push:
    branches:
      - master

jobs:
  Explore-Gitea-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: set-up
        uses: actions/setup-node@v3
        with:
          node-version: '18-nightly'
      - run: |
          npm config -g set registry https://registry.npmmirror.com
          npm install
          npm build

